name: video_calling
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  agora_rtc_engine: ^6.3.2
  cupertino_icons: ^1.0.6
  firebase_analytics: ^11.2.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.1.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/animations/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
